baseURL = "https://dr-hailer.github.io/"
locale = "de-DE"
defaultContentLanguage = "de"
title = "Michael Hailer"
theme = "PaperMod"

[params]
description = "Die persönliche Website von Michael Hailer: Beiträge und Notizen."
author = "Michael Hailer"
hideAuthor = true
mainSections = ["posts"]
defaultTheme = "auto"
disableThemeToggle = false
disableSpecial1stPost = true
ShowReadingTime = false
ShowToc = false
ShowBreadCrumbs = false
ShowPostNavLinks = false
ShowCodeCopyButtons = true
ShowShareButtons = false

[[cascade]]
  [cascade.target]
  path = "/posts/**"
  kind = "page"
  [cascade.params]
  ShowReadingTime = true
  ShowPostNavLinks = true

[[cascade]]
  [cascade.target]
  path = "/about"
  [cascade.params]
  hideMeta = true

[menu]

  [[menu.main]]
  name = "Beiträge"
  url = "/posts/"
  weight = 10

  [[menu.main]]
  name = "Emacs"
  url = "/emacs/"
  weight = 15

  [[menu.main]]
  name = "Über mich"
  url = "/about/"
  weight = 20
