baseURL = "https://dr-hailer.github.io/"
locale = "de-DE"
defaultContentLanguage = "de"
title = "Michael Hailer"
theme = "PaperMod"

[params]
defaultTheme = "auto"
ShowReadingTime = true
ShowToc = true
ShowBreadCrumbs = true
ShowPostNavLinks = true
ShowCodeCopyButtons = true

[menu]

  [[menu.main]]
  name = "Beiträge"
  url = "/posts/"
  weight = 10

  [[menu.main]]
  name = "Tags"
  url = "/tags/"
  weight = 20

[[menu.main]]
name = "Über mich"
url = "/about/"
weight = 30
